---
- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ tomcat_packages }}"
  tags: tomcat
- name: Install index.html
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/index.html.j2
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: '0664'
  notify: restart tomcat
  tags: tomcat
